project_id = "axjqigkhcyzkqseuzasz"

[functions.n8n-webhook]
verify_jwt = false

[functions.create-professor]
verify_jwt = false

[functions.public-registration]
verify_jwt = false

[functions.resend-credentials]
verify_jwt = false

[functions.approve-student-registration]
verify_jwt = false

[functions.mp-create-payment]
verify_jwt = true

[functions.mp-webhook]
verify_jwt = false

[functions.suspend-overdue]
verify_jwt = false

[functions.pagarme-create-subscription]
verify_jwt = true

[functions.pagarme-webhook]
verify_jwt = false
